import numpy
from PIL import Image
import newtiles
import time

map = numpy.zeros((24,24))

#map 3d array used for tracking what tiles can be put at that given location. Everything starts as true

#1 is land
#2 is coast
#3 is water
#4 is rock
#5 is flower

#pretty sure this is 24x24 but i dont wanna check lol
mapBool = numpy.array([[[True, True, True, True, True], [True, True, True, True, True] ,[True, True, True, True, True] ,[True, True, True, True, True] ,[True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True]],
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]],
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]], 
                       [[True, True, True, True, True], [True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False],[True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, False], [True, True, True, True, True]],
                       [[True, True, True, True, True], [True, True, True, True, True] ,[True, True, True, True, True] ,[True, True, True, True, True] ,[True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True ] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True] , [True, True, True, True, True]]
                       ])


               
img = Image.new('RGB', (144, 144))

img.save('output2.png')
img.show
time.sleep(2)
while True:
    FLOWER_CHANCE, ROCK_CHANCE, WATER_CHANCE, COAST_CHANCE, LAND_CHANCE, xIndex, yIndex = newtiles.getLowestEntropy()
    print(xIndex, yIndex)
    newtiles.chooseTile(xIndex, yIndex, FLOWER_CHANCE, ROCK_CHANCE, WATER_CHANCE, COAST_CHANCE, LAND_CHANCE)
    img.show
    time.sleep(.1)

